name: Emma Chambless
description: Strategic Technology Leader | Engineered for Resilience. Built for Change.

# Personal info
avatar: https://github.com/ECBerry76.png
footer-links:
  linkedin: emma-chambless
  github: ECBerry76
  email: emma.chambless76@gmail.com

# Portfolio Settings
google_analytics:
  
# Build settings
markdown: kramdown
highlighter: rouge
